nome = input('Insira seu nome: ')
idade = input('Insira sua idade: ')
peso = input('Insira seu peso: ')
sexo = input('Insira seu sexo: ')
print('Boa tarde {} \nVocê tem {} anos, pesa {} kilos e seu sexo é {}'.format(nome, idade, peso, sexo))